development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: angjuly7
  pool: 5
  username: root
  password: root
  
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: angjuly7
  pool: 5
  username: root
  password: root
  
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: angjuly7
  pool: 5
  username: root
  password: root  
